/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package research;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah
 */
public class home extends javax.swing.JFrame {
    public static String USER_NAME;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisterPastientButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginButtin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        RegisterPastientButton.setText("Register");
        RegisterPastientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPastientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterPastientButton);
        RegisterPastientButton.setBounds(150, 410, 140, 25);

        jLabel4.setText("Don't have an account?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 370, 160, 40);
        jPanel1.add(username);
        username.setBounds(190, 70, 200, 40);
        jPanel1.add(pas);
        pas.setBounds(190, 130, 200, 40);

        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 70, 120, 40);

        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 170, 40);

        LoginButtin.setText("Login");
        LoginButtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtinActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButtin);
        LoginButtin.setBounds(150, 330, 140, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtinActionPerformed
        // TODO add your handling code here:
        USER_NAME = username.getText();
        String pass = pas.getText();
        try
        {
            if(USER_NAME.isEmpty())
                JOptionPane.showMessageDialog(this, "Please enter your username", "ERROR", JOptionPane.ERROR_MESSAGE);
            else if(pass.isEmpty())
                JOptionPane.showMessageDialog(this, "Please enter your password", "ERROR", JOptionPane.ERROR_MESSAGE);

            else{
                String dbHost = "jdbc:derby://localhost:1527/Database";
                String dbUsrname = "ziad";
                String dbPass = "123456";

                Connection myconobj = DriverManager.getConnection(dbHost, dbUsrname, dbPass);

                
                String usr_query, pass_query, pass_col;
                usr_query = "SELECT USER_ID FROM PATIENT WHERE USER_ID=(?)";
                pass_query = "SELECT PASSWORD FROM PATIENT WHERE USER_ID=(?)";
                pass_col = "PASSWORD";

                
                // check if the user name has been used before
                PreparedStatement pstmt = myconobj.prepareStatement(usr_query);
                pstmt.setString(1, USER_NAME);
                ResultSet rs = pstmt.executeQuery(); 
                if(!(rs.next()))
                    JOptionPane.showMessageDialog(this, "User name is wrong", "ERROR", JOptionPane.ERROR_MESSAGE);                    
                else{
                    // get user password
                    pstmt = myconobj.prepareStatement(pass_query);
                    pstmt.setString(1, USER_NAME);
                    rs = pstmt.executeQuery();
                    rs.next();
                    String db_pass = rs.getString(pass_col);
                    
                    // check password
                    if(db_pass.equals(pass)) {
                        // return to home page
                        mainpage p2 = new mainpage();
                        p2.setVisible(true);
                        p2.setTitle("mianpage");
                        this.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "password is wrong", "ERROR", JOptionPane.ERROR_MESSAGE);                    
                    }
                }
            }
        }
        catch(HeadlessException | SQLException e)
        {   
            System.out.println(e.getMessage());            
        }      
        
        /*Connection myconobj = null;
        Statement mystatobj = null;
        ResultSet myresobj = null;
        String query = "Select * from ABDO.PATIENT";    
    
        try {
            myconobj = DriverManager.getConnection("jdbc:derby://localhost:1527/MyDB", "abdo", "abdo");
            mystatobj = myconobj.createStatement();
            myresobj = mystatobj.executeQuery(query);
            boolean flag = false;
        
            while(myresobj.next())
            {
                String user = myresobj.getString("USERID");
                String pass = myresobj.getString("PASSWORD");

                if(user.equals(username.getText()) && pass.equals(pas.getText()))
                {
                    flag = true;
                }
                else
                {continue;}
            }
        
            if(flag==true)
            {
                this.dispose();
                mainpage mp = new mainpage();
                mp.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Please register first", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }*/
    }//GEN-LAST:event_LoginButtinActionPerformed

    private void RegisterPastientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPastientButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PatientRegister().setVisible(true);
    }//GEN-LAST:event_RegisterPastientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButtin;
    private javax.swing.JButton RegisterPastientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pas;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
