/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package research;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;

/**
 *
 * @author kcsstore.com
 */
public class Progress extends javax.swing.JFrame {

    /**
     * Creates new form Progress
     */
    public Progress() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(450, 550);
        DefaultListModel date=new DefaultListModel();
        DefaultListModel blood=new DefaultListModel();
        DefaultListModel glucose=new DefaultListModel();
        DefaultListModel urination=new DefaultListModel();
        DefaultListModel water=new DefaultListModel();
        DefaultListModel pulse=new DefaultListModel();
        dates.setModel(date);
        bloods.setModel(blood);
        glucoses.setModel(glucose);
        pulses.setModel(pulse);
        urinations.setModel(urination);
        waters.setModel(water);
        List<MedicalInfo> list=new ArrayList<>();
         list=selectAll();
        for(MedicalInfo m:list){
            date.addElement(m.getDate());
            blood.addElement(m.getBlood_pressure());
            glucose.addElement(m.getGloucose());
            urination.addElement(m.getUrination());
            water.addElement(m.getWater_amount());
            pulse.addElement(m.getPulse_rate());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        sss = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bloods = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        glucoses = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        urinations = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        pulses = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        dates = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        waters = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setText("Follow Your Progress");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Blood Pressure");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Gloucose");

        s.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        s.setText("Urination");

        sss.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sss.setText("Pulse rate");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Date");

        ee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ee.setText("Water Amount");

        bloods.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloods.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane1.setViewportView(bloods);

        glucoses.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        glucoses.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane2.setViewportView(glucoses);

        urinations.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        urinations.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane3.setViewportView(urinations);

        pulses.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pulses.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane4.setViewportView(pulses);

        dates.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dates.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane5.setViewportView(dates);

        waters.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        waters.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        waters.setForeground(new java.awt.Color(0, 0, 250));
        jScrollPane6.setViewportView(waters);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sss)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ee)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s)
                    .addComponent(sss)
                    .addComponent(jLabel5)
                    .addComponent(ee)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Progress().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bloods;
    private javax.swing.JList dates;
    private javax.swing.JLabel ee;
    private javax.swing.JList glucoses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList pulses;
    private javax.swing.JLabel s;
    private javax.swing.JLabel sss;
    private javax.swing.JList urinations;
    private javax.swing.JList waters;
    // End of variables declaration//GEN-END:variables

        private ArrayList<MedicalInfo> selectAll() throws SQLException{
            String dbHost = "jdbc:derby://localhost:1527/Database";
            String dbUsrname = "ziad";
            String dbPass = "123456";
            String USER_ID=home.USER_NAME;
            ResultSet resultSet;
            ArrayList<MedicalInfo> list=new ArrayList<>();
            String query = "SELECT * FROM MEDICAL_INFO WHERE USER_ID = ?";
            Connection myconobj = DriverManager.getConnection(dbHost, dbUsrname, dbPass);
            PreparedStatement pstmt = myconobj.prepareStatement(query);
            pstmt.setString(1, USER_ID);
            resultSet=pstmt.executeQuery();
            while(resultSet.next()){
           
            MedicalInfo m=new MedicalInfo();
            m.setGloucose(resultSet.getString("GLOUCOSE"));
            m.setDate(resultSet.getString("DATE"));
            m.setBlood_pressure(resultSet.getString("SYSTOLIC")+"/"+resultSet.getString("DIASTOLIC"));
            m.setUrination(resultSet.getString("URENATION"));
            m.setPulse_rate(resultSet.getString("PULSE_RATE"));
            m.setWater_amount(resultSet.getString("NUMBER_OF_WATER"));
            list.add(m); }
            resultSet.close();
            myconobj.close();
            return list;
            }

}
